<?php

$AC = ["Acrelândia",
"Assis Brasil",
"Brasiléia",
"Bujari",
"Capixaba",
"Cruzeiro do Sul",
"Epitaciolândia",
"Feijó",
"Jordão",
"Mâncio Lima",
"Manoel Urbano",
"Marechal Thaumaturgo",
"Plácido de Castro",
"Porto Walter",
"Rio Branco",
"Rodrigues Alves",
"Santa Rosa do Purus",
"Senador Guiomard",
"Sena Madureira",
"Tarauacá",
"Xapuri",
"Porto Acre"
];

$AL = ["Água Branca",
"Anadia",
"Arapiraca",
"Atalaia",
"Barra de Santo Antônio",
"Barra de São Miguel",
"Batalha",
"Belém",
"Belo Monte",
"Boca da Mata",
"Branquinha",
"Cacimbinhas",
"Cajueiro",
"Campestre",
"Campo Alegre",
"Campo Grande",
"Canapi",
"Capela",
"Carneiros",
"Chã Preta",
"Coité do Nóia",
"Colônia Leopoldina",
"Coqueiro Seco",
"Coruripe",
"Craíbas",
"Delmiro Gouveia",
"Dois Riachos",
"Estrela de Alagoas",
"Feira Grande",
"Feliz Deserto",
"Flexeiras",
"Girau do Ponciano",
"Ibateguara",
"Igaci",
"Igreja Nova",
"Inhapi",
"Jacaré Dos Homens",
"Jacuípe",
"Japaratinga",
"Jaramataia",
"Jequiá da Praia",
"Joaquim Gomes",
"Jundiá",
"Junqueiro",
"Lagoa da Canoa",
"Limoeiro de Anadia",
"Maceió",
"Major Isidoro",
"Maragogi",
"Maravilha",
"Marechal Deodoro",
"Maribondo",
"Mar Vermelho",
"Mata Grande",
"Matriz de Camaragibe",
"Messias",
"Minador do Negrão",
"Monteirópolis",
"Murici",
"Novo Lino",
"Olho D´água Das Flores",
"Olho D´água do Casado",
"Olho D´água Grande",
"Olivença",
"Ouro Branco",
"Palestina",
"Palmeira Dos Índios",
"Pão de Açúcar",
"Pariconha",
"Paripueira",
"Passo de Camaragibe",
"Paulo Jacinto",
"Penedo",
"Piaçabuçu",
"Pilar",
"Pindoba",
"Piranhas",
"Poço Das Trincheiras",
"Porto Calvo",
"Porto de Pedras",
"Porto Real do Colégio",
"Quebrangulo",
"Rio Largo",
"Roteiro",
"Santa Luzia do Norte",
"Santana do Ipanema",
"Santana do Mundaú",
"São Brás",
"São José da Laje",
"São José da Tapera",
"São Luís do Quitunde",
"São Miguel Dos Campos",
"São Miguel Dos Milagres",
"São Sebastião",
"Satuba",
"Senador Rui Palmeira",
"Tanque D´arca",
"Taquarana",
"Teotônio Vilela",
"Traipu",
"União Dos Palmares",
"Viçosa"
];

$AM = ["Alvarães",
"Amaturá",
"Anamã",
"Anori",
"Apuí",
"Atalaia do Norte",
"Autazes",
"Barcelos",
"Barreirinha",
"Benjamin Constant",
"Beruri",
"Boa Vista do Ramos",
"Boca do Acre",
"Borba",
"Caapiranga",
"Canutama",
"Carauari",
"Careiro",
"Careiro da Várzea",
"Coari",
"Codajás",
"Eirunepé",
"Envira",
"Fonte Boa",
"Guajará",
"Humaitá",
"Ipixuna",
"Iranduba",
"Itacoatiara",
"Itamarati",
"Itapiranga",
"Japurá",
"Juruá",
"Jutaí",
"Lábrea",
"Manacapuru",
"Manaquiri",
"Manaus",
"Manicoré",
"Maraã",
"Maués",
"Nhamundá",
"Nova Olinda do Norte",
"Novo Airão",
"Novo Aripuanã",
"Parintins",
"Pauini",
"Presidente Figueiredo",
"Rio Preto da Eva",
"Santa Isabel do Rio Negro",
"Santo Antônio do Içá",
"São Gabriel da Cachoeira",
"São Paulo de Olivença",
"São Sebastião do Uatumã",
"Silves",
"Tabatinga",
"Tapauá",
"Tefé",
"Tonantins",
"Uarini",
"Urucará",
"Urucurituba"
];

$AP = ["Serra do Navio",
"Amapá",
"Pedra Branca do Amapari",
"Calçoene",
"Cutias",
"Ferreira Gomes",
"Itaubal",
"Laranjal do Jari",
"Macapá",
"Mazagão",
"Oiapoque",
"Porto Grande",
"Pracuúba",
"Santana",
"Tartarugalzinho",
"Vitória do Jari",
];


